### ISSUE TITLE
Two Japan translations ongoing

### ISSUE THREAD

**Issue by ingbrzy** [ScratchBuild/MIUI8-XML-Japanese#6]
Hi guys.. why you dont cooperate and make one perfect japanese translation...? 

@ScratchBuild 
@schipperke

**Comment by schipperke** [comment]
Hi,ingbrzy
I've just received invitation from @ScratchBuild.
I'll push what I've translated to https://github.com/ScratchBuild/MIUI8-XML-Japanese.
Then I'll delete this repository for the avoidance of confusion.
We can begin a collaborative process very soon.
Any kinds of your advice and suggestions to me are always welcome and appreciated.

**Comment by ingbrzy** [comment]
OK great @schipperke !

Good luck and thank you for your effort..
